// Taste Finder — Configuration constants

const CONFIG = {
  PLACES_API_URL: "https://places.googleapis.com/v1/places:searchText",
  OPENROUTER_URL: "https://openrouter.ai/api/v1/chat/completions",
  PLACES_FIELD_MASK: [
    "places.displayName",
    "places.formattedAddress",
    "places.rating",
    "places.userRatingCount",
    "places.priceLevel",
    "places.primaryTypeDisplayName",
    "places.editorialSummary",
    "places.googleMapsUri",
    "places.websiteUri",
    "places.location",
    "places.types",
    "places.servesCoffee",
    "places.servesBeer",
    "places.servesWine",
    "places.servesCocktails",
    "places.servesBrunch",
    "places.servesDessert",
    "places.servesVegetarianFood",
    "places.outdoorSeating",
    "places.dineIn",
    "places.takeout",
    "places.reservable",
    "places.liveMusic",
    "places.goodForGroups",
    "places.businessStatus",
    "nextPageToken",
  ].join(","),
  CHUNK_SIZE: 100,
  RANK_BATCH_SIZE: 10,
  MAX_CANDIDATES: 50,
};
